### ISSUE TITLE
Issue with datetime fields

### ISSUE THREAD

**Issue by CF-FHB-X** [realiii/pygeopkg#6]
I've searched the main README for instructions on creating datetime fields, but unless there are other docs somewhere, I can't seem to find a solution for this. It seems that providing a `SQLFieldTypes.datetime` as the type for a field causes an error:

```python
from pygeopkg.core.geopkg import GeoPackage
from pygeopkg.core.srs import SRS
from pygeopkg.core.field import Field
from pygeopkg.shared.enumeration import GeometryType, SQLFieldTypes
import pathlib

gpkg = GeoPackage.create(pathlib.Path.home().joinpath("test_datetime.gpkg"))
srs_wkt = 'GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433],AUTHORITY["EPSG",4326]]'
srs = SRS("WGS84", "EPSG", 4326, srs_wkt)
fields = (
    Field('int_fld', SQLFieldTypes.integer),
    Field('date_fld', SQLFieldTypes.date),
    Field('datetime_fld', SQLFieldTypes.datetime)
)
fc = gpkg.create_feature_class(
    "test",
    srs,
    fields=fields,
    shape_type=GeometryType.point
)
```

This throws the following error:
```
Traceback (most recent call last):
  File "C:\temp\.venv\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-4e68b047d91e>", line 14, in <cell line: 14>
    fc = gpkg.create_feature_class(
  File "C:\temp\.venv\lib\site-packages\pygeopkg\core\geopkg.py", line 171, in create_feature_class
    self._create_feature_table(name, shape_type, fields)
  File "C:\temp\.venv\lib\site-packages\pygeopkg\core\geopkg.py", line 196, in _create_feature_table
    connection_execute(self.full_path, sql)
  File "C:\temp\.venv\lib\site-packages\pygeopkg\core\utils.py", line 30, in connection_execute
    result = conn.execute(sql)
sqlite3.OperationalError: near "(": syntax error
```

Dropping that `SQLFieldTypes.datetime` field, though, and everything works like a charm.

Am I just missing something like an argument for that datetime format?

**Comment by jlhumber** [comment]
@CF-FHB-X nothing you've missed, turns out that the `SQLFieldTypes.datetime` values was a `tuple` and not a `str`.  The correction has been pushed to the repository.  

You might also be interested in [fudgeo](https://github.com/realiii/fudgeo) which is a little more modern spin on geopackages (but is 3.x python only).

**Comment by CF-FHB-X** [comment]
Sweet - thanks! I will have a look at fudgeo, too, as we're Python 3-only. 

Thanks again!
Richard
